name: Show Crawler

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Step1-Checkout Repository
        uses: actions/checkout@v4

      - name: Step2-Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Step3-Call API
        run: |
          curl -s "https://csm.api.opentix.life/programs/2051591825313611777" \
          -o response.json

      - name: Step4-Extract Specific Content
        run: |
          curl "https://csm.api.opentix.life/programs/2051591825313611777" | 
          jq ".result.eventVenues[] | select(.id == \"2051593347817213953\").events[] | 
          select(.id | IN(\"2052682612679090177\",\"2052683047905329153\",\"2052682637388972033\",\"2052683057301188609\",\"2052683065424936961\",\"2052682652327120897\",\"2052683073990541313\")) |
          {showTime:((.startDateTime + 28800) | strftime(\"%Y-%m-%d %H:%M:%S\")) , quantity:.quantity.remainingQuantity, 
          sections:[.groupSections.default[] | select(.name | tostring | [contains(\"視線受限\"),contains(\"友善\"),contains(\"輪椅\")] | any | not) | {name:.name,quantity:.quantity.remainingQuantity}] }" 
          response.json > new.json

      - name: Step5-Compare JSON
        id: compare
        run: |
          if diff -q data/latest.json new.json > /dev/null; then
            echo "same=true" >> $GITHUB_OUTPUT
          else
            echo "same=false" >> $GITHUB_OUTPUT
          fi

      - name: Step6-Update Stored JSON
        if: steps.compare.outputs.same == 'false'
        run: |
          cp new.json data/latest.json

      - name: Step7-Commit Changes
        if: steps.compare.outputs.same == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/latest.json

          git commit -m "Update API data"

          git push

      - name: Step8-Send Mail Notification
        if: steps.compare.outputs.same == 'false'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: API Data Changed
          to: yourmail@example.com
          from: GitHub Actions

          body: |
            API內容已變更

            最新內容：

            ${{ steps.compare.outputs.same }}
